/*
 * generated by Xtext 2.9.0
 */
package de.htwberlin.selabs.pml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PmlDslStandaloneSetup extends PmlDslStandaloneSetupGenerated {

	def static void doSetup() {
		new PmlDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
