/*
 * generated by Xtext 2.9.0
 */
package de.htwberlin.selabs.pml


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PmlDslRuntimeModule extends AbstractPmlDslRuntimeModule {
}
