/*
 * generated by Xtext 2.9.0
 */
package de.htwberlin.selabs.rcrs


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RcrsDslRuntimeModule extends AbstractRcrsDslRuntimeModule {
}
