/*
 * generated by Xtext 2.9.0
 */
package de.htwberlin.selabs.rcrs


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RcrsDslStandaloneSetup extends RcrsDslStandaloneSetupGenerated {

	def static void doSetup() {
		new RcrsDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
